# Protocol

<p style="color:red">NB! This protocol was efficient for the identification of particles under the stereo microscope but it needs to be adjusted if the samples will be used for the Raman. Digestion needs to be more efficient if the samples are used for the RAMAN. Since there can be a lot of sand in some samples a density separation might be applicable. If there is a lot of organic matter left on the filter digestion time/method might need to be adjusted.</p>

# Equipment

Equipment
* [Zooplankton net](https://www.nhbs.com/plankton-net-250mm-frame-32mm-filter?bkfno=184244) (100 µm mesh size)
* 1 litre plastic container **(from Samhentir (L-11-1000 Dós 1000 ml gl. 133 mm))**
* Biological Safety Cabinet (MSC Advantage 12 BSC)
* Sterile petri dishes (plastic (Polystyrene))
* Forceps
* Glass filtration unit including vacuum pump
* Filters; whatman nitrocellulose filters 0.45 um 47 mm
* Filters; durapore membrane filters 0.22 um, GV, 47 mm
* Temperature controlled oven
* Freeze dryer
* Pre-weighed 250 ml Erlenmeyer flasks
* Steel mesh, 125 µm mesh size
* Stereo microscope (Olympus SZX16)
* Camera (Leica DMC 2900)


## Reagents

* Hydrogen peroxide 10 % solution (NB: Use gloves and goggles! 282 ml of 35.5 % H2O2 up to 1 litre of MilliQ water. Filter with 0.22 um filter under the clean bench)
* Potassium hydroxide 10 % solution (NB: Use gloves and goggles! 100 g of potassium pellets up to 1 litre of MilliQ water. Filter with 0.22 um filter under the clean bench)
* MilliQ water

#Preparations

Prior to sampling the sampling containers (1 l) and the Erlenmeyer flasks (250 ml) are washed with hot water, then two times with milliQ water and then once with milliQ water under the clean bench. 
In correspondence with Dr. Joao Frias glass ware are treated like this: “we use honey and jam jars, which we wash, rinse and clean with milliQ or ultrapure water, before decontaminating them in an acid bath (0.5-1%). After this process, the jars are washed and rinsed again with ultrapure water.” 
In the BASEMAN protocol Nitric acid (1 %) is used to decontaminate the glass ware before the glass is rinsed with water before use. Ideally it should dry up-side-down for airborne microplastics not to accumulate in it.
The containers and flasks need to be closed with a lid or aluminium foil whenever they are not handled under the clean bench. 
The Erlenmeyer flasks have to be dried in the oven after rinsing to be able to take the tare. Record the tare! Remember that the flasks need to be covered with aluminium foil after they have been rinsed. 
<p style="color:red">All the solutions which will be added to the samples have to be filtered under the clean bench with a 0.22 um filter.</p>


# Sampling on board

Recorded parameters in the past were: 

* Temperature, 
* salinity, 
* sampling coordinates and 
* general weather conditions.

According to the baseman protocol other environmental variables that might help elucidate the influences on the recorded presence and concentration of microplastics in seawater:

* Wind speed and direction
* Sea state; wave height
* Amount of macrodebris 
* Oxygen
* Chlorophyll-a
* Turbidity, etc.

Samples are taken from the water column from 20 m to the surface with the zooplankton net. The plankton net has a diameter of 30 cm. The volume sampled is calculated like that: volume = π × r^2^ × h which means π × 0.15m × 0.15m × 20m which results in 1.4 m^3^ or 1413 litres of water sampled. 
The net should be rinsed with tap water and stored in a corn bag prior to sampling to avoid the collection of dust inside the net. 
*Mussel larvae sampling (or any other sampling) should be performed before the plastic samples are taken to give the net some extra rinsing.* 
The content of the net is flushed into a 1 litre plastic container.
During sampling it is recommended wear clothing made of cotton and it is important not to use plastic ropes which could shed fibres during sampling. Monofilament cord or a metal wire is preferred.
It is also important to make sure the net is not pulled under the boat to avoid contamination from the paint of the boat.

# Blanks

Three different types of blanks are taken with each sampling/processing.

1. Blank taken on board of the vessel to document contamination during sampling.
2. Blank from processing taken under the clean bench to document contamination from chemicals/water/flasks during the process.
3. Blank from the clean bench taken by placing three wet filter papers (in a petri dish) under the clean bench during the entire processing of the samples. 

*Blank 1*: A rinsed 1 litre container is filled in the lab with around 500 ml of MilliQ water. This container is left open during the entire microplastic sampling to collect any airborne contamination. The container is closed after sampling (at the same time as the sampling containers on board are closed) and returned to the lab. In the lab the sample is filtered straight onto a filter (without digestion) and checked for contaminations.

*Blank 2* is prepared by using a pre-weighed Erlenmeyer flask which is filled with approximately the same volume of MilliQ water as used for the samples. The blank is frozen, freeze-dried, and processed like the samples (chemicals added, incubated, filtered and transferred onto filter).

*Blank 3* is prepared by using three filters (checked under the stereo microscope for contamination before using it) which are placed in an open petri dish, wettened with MilliQ water and placed under the clean bench during processing. 

# Processing in the laboratory

<p style="color:red">NB: Authors from the baseman protocol recommend to not exceed an incubation temperature of more than 40 °C as well as not exceeding a concentration of 10 % for KOH and H2O2, however other protocols go above this temperature/time.</p>

The samples/blank are stored in the fridge (for short time storage) or in the freezer (for long time storage). 

If the samples are frozen, defrost them at room temperature. If the quantity of organic content is too high to allow direct examination, samples are pre-filtered under the BSC using a 125 µm steal sieve and carefully transferred to a pre-weighed 250 ml Erlenmeyer flasks.

The samples are then covered with aluminium foil, frozen at -70 °C and placed into the freeze dryer until dry.

The weight of the Erlenmeyer flasks should be taken once they reached room temperature. Subtract the recorded tare and document the mass of organic matter. 

## Sample digestion

A sample pre-treatment consisting of digestion of the soft tissues in potassium hydroxide should be performed. 

### 10 % KOH digestion

At least 20 ml of 10 % potassium hydroxide solution is added to each flask (including blank). Make sure the entire sample is covered with solution (if there is a lot of organic material more solution might be needed to cover the material). The mixture is placed in a temperature-controlled oven at 40 °C. It is very important to not exceed this temperature. The treatment of the samples continues at 40 °C for a maximum of 72 hours.

### 10 % H2O2 digestion

Following the KOH digestion, if not all the matter was digested, an additional step, using hydrogen peroxide could be necessary. The same volume of hydrogen peroxide (10 % solution) as used in the previous step (potassium hydroxide) is added to the flask (if 20 ml of KOH solution was added in the first step, 20 ml of hydrogen peroxide should be added). Hydrogen peroxide solution is added to oxidize and digest the remaining material. The mixture is placed in a temperature-controlled oven at 40 °C for a maximum of 72 hours.

### Density separation

An additional density separation step can be added if there is a lot of sand/organic matter left on the filter. This can be carried out according to the Baseman protocol or any other applicable protocol.

### Filtration of samples

To minimize the exposure of chemicals on the filter paper the mixture is first filtered through a 125 µm steel mesh (same as in the previous step). The remaining particles are then transferred onto a nitrocellulose filter. 

### Storage of filters

After the samples are on the filters are put into a sterile and labelled petri dish dried and kept at room temperature until dry. Once dry they can be closed with parafilm and stored in the freezer until microscopic observations. **If the samples are stored wet at room temperature mould can form on the filters**.


# Identification 

Relevant criteria to take into consideration during identification include physical (size, type, colour) and chemical properties.
Until now only stereo microscopic observations can be carried out at BioPol so only physical properties are included in the identification.
Each microplastic is photographed under the stereo microscope using the Leica camera and measured with image J.

1. Size: data should be recorded in three size classes, 1-100 µm, 100-350 µm, 350 µm-5 mm. Note for measurements: Fibre and filament: length and diameter, Fragment, film, paint sheet and rubber: perimeter, area, width and length .
2. Pellet and microbead: perimeter and diameter
3. Type: pellet, fragment, fibre, film, rope and filaments, microbeads (perfect spheres), sponge/foam, rubber
4. Color: Black, blue, white, transparent, red, green, multicolour, others.

# Reporting results

Reporting units are extremely important to allow comparison among studies. The proposed reporting units for microplastics retrieved from water samples are:

1. No.MPs per area (#particles km-2 or # particles m-2)
2. No.MPs per volume (#particles m-3)
3. Mass of MP per area (gMP km-2 or gMP m-2)
4. Mass of MP per volume (gMP l-3 or gMP m-3)

The only unit making sense in our study so far is 2: No.MPs per volume (particles/m^-3^)
